// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: person.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_person_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_person_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3012000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3012004 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_table_driven.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/inlined_string_field.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/map.h>  // IWYU pragma: export
#include <google/protobuf/map_entry.h>
#include <google/protobuf/map_field_inl.h>
#include <google/protobuf/generated_enum_reflection.h>
#include <google/protobuf/service.h>
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_person_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_person_2eproto {
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTableField entries[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::AuxillaryParseTableField aux[]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::ParseTable schema[4]
    PROTOBUF_SECTION_VARIABLE(protodesc_cold);
  static const ::PROTOBUF_NAMESPACE_ID::internal::FieldMetadata field_metadata[];
  static const ::PROTOBUF_NAMESPACE_ID::internal::SerializationTable serialization_table[];
  static const ::PROTOBUF_NAMESPACE_ID::uint32 offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_person_2eproto;
namespace person {
class PersonRequest;
class PersonRequestDefaultTypeInternal;
extern PersonRequestDefaultTypeInternal _PersonRequest_default_instance_;
class PersonResponse;
class PersonResponseDefaultTypeInternal;
extern PersonResponseDefaultTypeInternal _PersonResponse_default_instance_;
class Student;
class StudentDefaultTypeInternal;
extern StudentDefaultTypeInternal _Student_default_instance_;
class Student_OtherEntry_DoNotUse;
class Student_OtherEntry_DoNotUseDefaultTypeInternal;
extern Student_OtherEntry_DoNotUseDefaultTypeInternal _Student_OtherEntry_DoNotUse_default_instance_;
}  // namespace person
PROTOBUF_NAMESPACE_OPEN
template<> ::person::PersonRequest* Arena::CreateMaybeMessage<::person::PersonRequest>(Arena*);
template<> ::person::PersonResponse* Arena::CreateMaybeMessage<::person::PersonResponse>(Arena*);
template<> ::person::Student* Arena::CreateMaybeMessage<::person::Student>(Arena*);
template<> ::person::Student_OtherEntry_DoNotUse* Arena::CreateMaybeMessage<::person::Student_OtherEntry_DoNotUse>(Arena*);
PROTOBUF_NAMESPACE_CLOSE
namespace person {

enum SexType : int {
  unkonw = 0,
  man = 1,
  woman = 2,
  SexType_INT_MIN_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::min(),
  SexType_INT_MAX_SENTINEL_DO_NOT_USE_ = std::numeric_limits<::PROTOBUF_NAMESPACE_ID::int32>::max()
};
bool SexType_IsValid(int value);
constexpr SexType SexType_MIN = unkonw;
constexpr SexType SexType_MAX = woman;
constexpr int SexType_ARRAYSIZE = SexType_MAX + 1;

const ::PROTOBUF_NAMESPACE_ID::EnumDescriptor* SexType_descriptor();
template<typename T>
inline const std::string& SexType_Name(T enum_t_value) {
  static_assert(::std::is_same<T, SexType>::value ||
    ::std::is_integral<T>::value,
    "Incorrect type passed to function SexType_Name.");
  return ::PROTOBUF_NAMESPACE_ID::internal::NameOfEnum(
    SexType_descriptor(), enum_t_value);
}
inline bool SexType_Parse(
    const std::string& name, SexType* value) {
  return ::PROTOBUF_NAMESPACE_ID::internal::ParseNamedEnum<SexType>(
    SexType_descriptor(), name, value);
}
// ===================================================================

class Student_OtherEntry_DoNotUse : public ::PROTOBUF_NAMESPACE_ID::internal::MapEntry<Student_OtherEntry_DoNotUse, 
    ::PROTOBUF_NAMESPACE_ID::int32, std::string,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_INT32,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
    0 > {
public:
  typedef ::PROTOBUF_NAMESPACE_ID::internal::MapEntry<Student_OtherEntry_DoNotUse, 
    ::PROTOBUF_NAMESPACE_ID::int32, std::string,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_INT32,
    ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
    0 > SuperType;
  Student_OtherEntry_DoNotUse();
  Student_OtherEntry_DoNotUse(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  void MergeFrom(const Student_OtherEntry_DoNotUse& other);
  static const Student_OtherEntry_DoNotUse* internal_default_instance() { return reinterpret_cast<const Student_OtherEntry_DoNotUse*>(&_Student_OtherEntry_DoNotUse_default_instance_); }
  static bool ValidateKey(void*) { return true; }
  static bool ValidateValue(std::string* s) {
    return ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::VerifyUtf8String(s->data(), static_cast<int>(s->size()), ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::PARSE, "person.Student.OtherEntry.value");
 }
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& other) final;
  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_person_2eproto);
    return ::descriptor_table_person_2eproto.file_level_metadata[0];
  }

  public:
};

// -------------------------------------------------------------------

class Student PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:person.Student) */ {
 public:
  inline Student() : Student(nullptr) {};
  virtual ~Student();

  Student(const Student& from);
  Student(Student&& from) noexcept
    : Student() {
    *this = ::std::move(from);
  }

  inline Student& operator=(const Student& from) {
    CopyFrom(from);
    return *this;
  }
  inline Student& operator=(Student&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const Student& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const Student* internal_default_instance() {
    return reinterpret_cast<const Student*>(
               &_Student_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(Student& a, Student& b) {
    a.Swap(&b);
  }
  inline void Swap(Student* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Student* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline Student* New() const final {
    return CreateMaybeMessage<Student>(nullptr);
  }

  Student* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<Student>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const Student& from);
  void MergeFrom(const Student& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Student* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "person.Student";
  }
  protected:
  explicit Student(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_person_2eproto);
    return ::descriptor_table_person_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------


  // accessors -------------------------------------------------------

  enum : int {
    kScoreFieldNumber = 4,
    kOtherFieldNumber = 5,
    kNameFieldNumber = 2,
    kSnFieldNumber = 1,
    kSexFieldNumber = 3,
  };
  // repeated float score = 4;
  int score_size() const;
  private:
  int _internal_score_size() const;
  public:
  void clear_score();
  private:
  float _internal_score(int index) const;
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
      _internal_score() const;
  void _internal_add_score(float value);
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
      _internal_mutable_score();
  public:
  float score(int index) const;
  void set_score(int index, float value);
  void add_score(float value);
  const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
      score() const;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
      mutable_score();

  // map<int32, string> other = 5;
  int other_size() const;
  private:
  int _internal_other_size() const;
  public:
  void clear_other();
  private:
  const ::PROTOBUF_NAMESPACE_ID::Map< ::PROTOBUF_NAMESPACE_ID::int32, std::string >&
      _internal_other() const;
  ::PROTOBUF_NAMESPACE_ID::Map< ::PROTOBUF_NAMESPACE_ID::int32, std::string >*
      _internal_mutable_other();
  public:
  const ::PROTOBUF_NAMESPACE_ID::Map< ::PROTOBUF_NAMESPACE_ID::int32, std::string >&
      other() const;
  ::PROTOBUF_NAMESPACE_ID::Map< ::PROTOBUF_NAMESPACE_ID::int32, std::string >*
      mutable_other();

  // string name = 2;
  void clear_name();
  const std::string& name() const;
  void set_name(const std::string& value);
  void set_name(std::string&& value);
  void set_name(const char* value);
  void set_name(const char* value, size_t size);
  std::string* mutable_name();
  std::string* release_name();
  void set_allocated_name(std::string* name);
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  std::string* unsafe_arena_release_name();
  GOOGLE_PROTOBUF_RUNTIME_DEPRECATED("The unsafe_arena_ accessors for"
  "    string fields are deprecated and will be removed in a"
  "    future release.")
  void unsafe_arena_set_allocated_name(
      std::string* name);
  private:
  const std::string& _internal_name() const;
  void _internal_set_name(const std::string& value);
  std::string* _internal_mutable_name();
  public:

  // int32 sn = 1;
  void clear_sn();
  ::PROTOBUF_NAMESPACE_ID::int32 sn() const;
  void set_sn(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_sn() const;
  void _internal_set_sn(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // .person.SexType sex = 3;
  void clear_sex();
  ::person::SexType sex() const;
  void set_sex(::person::SexType value);
  private:
  ::person::SexType _internal_sex() const;
  void _internal_set_sex(::person::SexType value);
  public:

  // @@protoc_insertion_point(class_scope:person.Student)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::RepeatedField< float > score_;
  mutable std::atomic<int> _score_cached_byte_size_;
  ::PROTOBUF_NAMESPACE_ID::internal::MapField<
      Student_OtherEntry_DoNotUse,
      ::PROTOBUF_NAMESPACE_ID::int32, std::string,
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_INT32,
      ::PROTOBUF_NAMESPACE_ID::internal::WireFormatLite::TYPE_STRING,
      0 > other_;
  ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr name_;
  ::PROTOBUF_NAMESPACE_ID::int32 sn_;
  int sex_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_person_2eproto;
};
// -------------------------------------------------------------------

class PersonRequest PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:person.PersonRequest) */ {
 public:
  inline PersonRequest() : PersonRequest(nullptr) {};
  virtual ~PersonRequest();

  PersonRequest(const PersonRequest& from);
  PersonRequest(PersonRequest&& from) noexcept
    : PersonRequest() {
    *this = ::std::move(from);
  }

  inline PersonRequest& operator=(const PersonRequest& from) {
    CopyFrom(from);
    return *this;
  }
  inline PersonRequest& operator=(PersonRequest&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const PersonRequest& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const PersonRequest* internal_default_instance() {
    return reinterpret_cast<const PersonRequest*>(
               &_PersonRequest_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(PersonRequest& a, PersonRequest& b) {
    a.Swap(&b);
  }
  inline void Swap(PersonRequest* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PersonRequest* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline PersonRequest* New() const final {
    return CreateMaybeMessage<PersonRequest>(nullptr);
  }

  PersonRequest* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<PersonRequest>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const PersonRequest& from);
  void MergeFrom(const PersonRequest& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(PersonRequest* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "person.PersonRequest";
  }
  protected:
  explicit PersonRequest(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_person_2eproto);
    return ::descriptor_table_person_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kSnFieldNumber = 1,
  };
  // int32 sn = 1;
  void clear_sn();
  ::PROTOBUF_NAMESPACE_ID::int32 sn() const;
  void set_sn(::PROTOBUF_NAMESPACE_ID::int32 value);
  private:
  ::PROTOBUF_NAMESPACE_ID::int32 _internal_sn() const;
  void _internal_set_sn(::PROTOBUF_NAMESPACE_ID::int32 value);
  public:

  // @@protoc_insertion_point(class_scope:person.PersonRequest)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::PROTOBUF_NAMESPACE_ID::int32 sn_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_person_2eproto;
};
// -------------------------------------------------------------------

class PersonResponse PROTOBUF_FINAL :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:person.PersonResponse) */ {
 public:
  inline PersonResponse() : PersonResponse(nullptr) {};
  virtual ~PersonResponse();

  PersonResponse(const PersonResponse& from);
  PersonResponse(PersonResponse&& from) noexcept
    : PersonResponse() {
    *this = ::std::move(from);
  }

  inline PersonResponse& operator=(const PersonResponse& from) {
    CopyFrom(from);
    return *this;
  }
  inline PersonResponse& operator=(PersonResponse&& from) noexcept {
    if (GetArena() == from.GetArena()) {
      if (this != &from) InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return GetMetadataStatic().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return GetMetadataStatic().reflection;
  }
  static const PersonResponse& default_instance();

  static void InitAsDefaultInstance();  // FOR INTERNAL USE ONLY
  static inline const PersonResponse* internal_default_instance() {
    return reinterpret_cast<const PersonResponse*>(
               &_PersonResponse_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(PersonResponse& a, PersonResponse& b) {
    a.Swap(&b);
  }
  inline void Swap(PersonResponse* other) {
    if (other == this) return;
    if (GetArena() == other->GetArena()) {
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(PersonResponse* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetArena() == other->GetArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  inline PersonResponse* New() const final {
    return CreateMaybeMessage<PersonResponse>(nullptr);
  }

  PersonResponse* New(::PROTOBUF_NAMESPACE_ID::Arena* arena) const final {
    return CreateMaybeMessage<PersonResponse>(arena);
  }
  void CopyFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void MergeFrom(const ::PROTOBUF_NAMESPACE_ID::Message& from) final;
  void CopyFrom(const PersonResponse& from);
  void MergeFrom(const PersonResponse& from);
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  ::PROTOBUF_NAMESPACE_ID::uint8* _InternalSerialize(
      ::PROTOBUF_NAMESPACE_ID::uint8* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _cached_size_.Get(); }

  private:
  inline void SharedCtor();
  inline void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(PersonResponse* other);
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "person.PersonResponse";
  }
  protected:
  explicit PersonResponse(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  private:
  static void ArenaDtor(void* object);
  inline void RegisterArenaDtor(::PROTOBUF_NAMESPACE_ID::Arena* arena);
  public:

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;
  private:
  static ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadataStatic() {
    ::PROTOBUF_NAMESPACE_ID::internal::AssignDescriptors(&::descriptor_table_person_2eproto);
    return ::descriptor_table_person_2eproto.file_level_metadata[kIndexInFileMessages];
  }

  public:

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kStudentFieldNumber = 1,
  };
  // .person.Student student = 1;
  bool has_student() const;
  private:
  bool _internal_has_student() const;
  public:
  void clear_student();
  const ::person::Student& student() const;
  ::person::Student* release_student();
  ::person::Student* mutable_student();
  void set_allocated_student(::person::Student* student);
  private:
  const ::person::Student& _internal_student() const;
  ::person::Student* _internal_mutable_student();
  public:
  void unsafe_arena_set_allocated_student(
      ::person::Student* student);
  ::person::Student* unsafe_arena_release_student();

  // @@protoc_insertion_point(class_scope:person.PersonResponse)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  ::person::Student* student_;
  mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  friend struct ::TableStruct_person_2eproto;
};
// ===================================================================

class PersonService_Stub;

class PersonService : public ::PROTOBUF_NAMESPACE_ID::Service {
 protected:
  // This class should be treated as an abstract interface.
  inline PersonService() {};
 public:
  virtual ~PersonService();

  typedef PersonService_Stub Stub;

  static const ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor* descriptor();

  virtual void getPerson(::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                       const ::person::PersonRequest* request,
                       ::person::PersonResponse* response,
                       ::google::protobuf::Closure* done);

  // implements Service ----------------------------------------------

  const ::PROTOBUF_NAMESPACE_ID::ServiceDescriptor* GetDescriptor();
  void CallMethod(const ::PROTOBUF_NAMESPACE_ID::MethodDescriptor* method,
                  ::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                  const ::PROTOBUF_NAMESPACE_ID::Message* request,
                  ::PROTOBUF_NAMESPACE_ID::Message* response,
                  ::google::protobuf::Closure* done);
  const ::PROTOBUF_NAMESPACE_ID::Message& GetRequestPrototype(
    const ::PROTOBUF_NAMESPACE_ID::MethodDescriptor* method) const;
  const ::PROTOBUF_NAMESPACE_ID::Message& GetResponsePrototype(
    const ::PROTOBUF_NAMESPACE_ID::MethodDescriptor* method) const;

 private:
  GOOGLE_DISALLOW_EVIL_CONSTRUCTORS(PersonService);
};

class PersonService_Stub : public PersonService {
 public:
  PersonService_Stub(::PROTOBUF_NAMESPACE_ID::RpcChannel* channel);
  PersonService_Stub(::PROTOBUF_NAMESPACE_ID::RpcChannel* channel,
                   ::PROTOBUF_NAMESPACE_ID::Service::ChannelOwnership ownership);
  ~PersonService_Stub();

  inline ::PROTOBUF_NAMESPACE_ID::RpcChannel* channel() { return channel_; }

  // implements PersonService ------------------------------------------

  void getPerson(::PROTOBUF_NAMESPACE_ID::RpcController* controller,
                       const ::person::PersonRequest* request,
                       ::person::PersonResponse* response,
                       ::google::protobuf::Closure* done);
 private:
  ::PROTOBUF_NAMESPACE_ID::RpcChannel* channel_;
  bool owns_channel_;
  GOOGLE_DISALLOW_EVIL_CONSTRUCTORS(PersonService_Stub);
};


// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// Student

// int32 sn = 1;
inline void Student::clear_sn() {
  sn_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 Student::_internal_sn() const {
  return sn_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 Student::sn() const {
  // @@protoc_insertion_point(field_get:person.Student.sn)
  return _internal_sn();
}
inline void Student::_internal_set_sn(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  sn_ = value;
}
inline void Student::set_sn(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_sn(value);
  // @@protoc_insertion_point(field_set:person.Student.sn)
}

// string name = 2;
inline void Student::clear_name() {
  name_.ClearToEmpty(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline const std::string& Student::name() const {
  // @@protoc_insertion_point(field_get:person.Student.name)
  return _internal_name();
}
inline void Student::set_name(const std::string& value) {
  _internal_set_name(value);
  // @@protoc_insertion_point(field_set:person.Student.name)
}
inline std::string* Student::mutable_name() {
  // @@protoc_insertion_point(field_mutable:person.Student.name)
  return _internal_mutable_name();
}
inline const std::string& Student::_internal_name() const {
  return name_.Get();
}
inline void Student::_internal_set_name(const std::string& value) {
  
  name_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), value, GetArena());
}
inline void Student::set_name(std::string&& value) {
  
  name_.Set(
    &::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::move(value), GetArena());
  // @@protoc_insertion_point(field_set_rvalue:person.Student.name)
}
inline void Student::set_name(const char* value) {
  GOOGLE_DCHECK(value != nullptr);
  
  name_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(value),
              GetArena());
  // @@protoc_insertion_point(field_set_char:person.Student.name)
}
inline void Student::set_name(const char* value,
    size_t size) {
  
  name_.Set(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), ::std::string(
      reinterpret_cast<const char*>(value), size), GetArena());
  // @@protoc_insertion_point(field_set_pointer:person.Student.name)
}
inline std::string* Student::_internal_mutable_name() {
  
  return name_.Mutable(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline std::string* Student::release_name() {
  // @@protoc_insertion_point(field_release:person.Student.name)
  return name_.Release(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), GetArena());
}
inline void Student::set_allocated_name(std::string* name) {
  if (name != nullptr) {
    
  } else {
    
  }
  name_.SetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(), name,
      GetArena());
  // @@protoc_insertion_point(field_set_allocated:person.Student.name)
}
inline std::string* Student::unsafe_arena_release_name() {
  // @@protoc_insertion_point(field_unsafe_arena_release:person.Student.name)
  GOOGLE_DCHECK(GetArena() != nullptr);
  
  return name_.UnsafeArenaRelease(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      GetArena());
}
inline void Student::unsafe_arena_set_allocated_name(
    std::string* name) {
  GOOGLE_DCHECK(GetArena() != nullptr);
  if (name != nullptr) {
    
  } else {
    
  }
  name_.UnsafeArenaSetAllocated(&::PROTOBUF_NAMESPACE_ID::internal::GetEmptyStringAlreadyInited(),
      name, GetArena());
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:person.Student.name)
}

// .person.SexType sex = 3;
inline void Student::clear_sex() {
  sex_ = 0;
}
inline ::person::SexType Student::_internal_sex() const {
  return static_cast< ::person::SexType >(sex_);
}
inline ::person::SexType Student::sex() const {
  // @@protoc_insertion_point(field_get:person.Student.sex)
  return _internal_sex();
}
inline void Student::_internal_set_sex(::person::SexType value) {
  
  sex_ = value;
}
inline void Student::set_sex(::person::SexType value) {
  _internal_set_sex(value);
  // @@protoc_insertion_point(field_set:person.Student.sex)
}

// repeated float score = 4;
inline int Student::_internal_score_size() const {
  return score_.size();
}
inline int Student::score_size() const {
  return _internal_score_size();
}
inline void Student::clear_score() {
  score_.Clear();
}
inline float Student::_internal_score(int index) const {
  return score_.Get(index);
}
inline float Student::score(int index) const {
  // @@protoc_insertion_point(field_get:person.Student.score)
  return _internal_score(index);
}
inline void Student::set_score(int index, float value) {
  score_.Set(index, value);
  // @@protoc_insertion_point(field_set:person.Student.score)
}
inline void Student::_internal_add_score(float value) {
  score_.Add(value);
}
inline void Student::add_score(float value) {
  _internal_add_score(value);
  // @@protoc_insertion_point(field_add:person.Student.score)
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
Student::_internal_score() const {
  return score_;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >&
Student::score() const {
  // @@protoc_insertion_point(field_list:person.Student.score)
  return _internal_score();
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
Student::_internal_mutable_score() {
  return &score_;
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedField< float >*
Student::mutable_score() {
  // @@protoc_insertion_point(field_mutable_list:person.Student.score)
  return _internal_mutable_score();
}

// map<int32, string> other = 5;
inline int Student::_internal_other_size() const {
  return other_.size();
}
inline int Student::other_size() const {
  return _internal_other_size();
}
inline void Student::clear_other() {
  other_.Clear();
}
inline const ::PROTOBUF_NAMESPACE_ID::Map< ::PROTOBUF_NAMESPACE_ID::int32, std::string >&
Student::_internal_other() const {
  return other_.GetMap();
}
inline const ::PROTOBUF_NAMESPACE_ID::Map< ::PROTOBUF_NAMESPACE_ID::int32, std::string >&
Student::other() const {
  // @@protoc_insertion_point(field_map:person.Student.other)
  return _internal_other();
}
inline ::PROTOBUF_NAMESPACE_ID::Map< ::PROTOBUF_NAMESPACE_ID::int32, std::string >*
Student::_internal_mutable_other() {
  return other_.MutableMap();
}
inline ::PROTOBUF_NAMESPACE_ID::Map< ::PROTOBUF_NAMESPACE_ID::int32, std::string >*
Student::mutable_other() {
  // @@protoc_insertion_point(field_mutable_map:person.Student.other)
  return _internal_mutable_other();
}

// -------------------------------------------------------------------

// PersonRequest

// int32 sn = 1;
inline void PersonRequest::clear_sn() {
  sn_ = 0;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 PersonRequest::_internal_sn() const {
  return sn_;
}
inline ::PROTOBUF_NAMESPACE_ID::int32 PersonRequest::sn() const {
  // @@protoc_insertion_point(field_get:person.PersonRequest.sn)
  return _internal_sn();
}
inline void PersonRequest::_internal_set_sn(::PROTOBUF_NAMESPACE_ID::int32 value) {
  
  sn_ = value;
}
inline void PersonRequest::set_sn(::PROTOBUF_NAMESPACE_ID::int32 value) {
  _internal_set_sn(value);
  // @@protoc_insertion_point(field_set:person.PersonRequest.sn)
}

// -------------------------------------------------------------------

// PersonResponse

// .person.Student student = 1;
inline bool PersonResponse::_internal_has_student() const {
  return this != internal_default_instance() && student_ != nullptr;
}
inline bool PersonResponse::has_student() const {
  return _internal_has_student();
}
inline void PersonResponse::clear_student() {
  if (GetArena() == nullptr && student_ != nullptr) {
    delete student_;
  }
  student_ = nullptr;
}
inline const ::person::Student& PersonResponse::_internal_student() const {
  const ::person::Student* p = student_;
  return p != nullptr ? *p : *reinterpret_cast<const ::person::Student*>(
      &::person::_Student_default_instance_);
}
inline const ::person::Student& PersonResponse::student() const {
  // @@protoc_insertion_point(field_get:person.PersonResponse.student)
  return _internal_student();
}
inline void PersonResponse::unsafe_arena_set_allocated_student(
    ::person::Student* student) {
  if (GetArena() == nullptr) {
    delete reinterpret_cast<::PROTOBUF_NAMESPACE_ID::MessageLite*>(student_);
  }
  student_ = student;
  if (student) {
    
  } else {
    
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:person.PersonResponse.student)
}
inline ::person::Student* PersonResponse::release_student() {
  auto temp = unsafe_arena_release_student();
  if (GetArena() != nullptr) {
    temp = ::PROTOBUF_NAMESPACE_ID::internal::DuplicateIfNonNull(temp);
  }
  return temp;
}
inline ::person::Student* PersonResponse::unsafe_arena_release_student() {
  // @@protoc_insertion_point(field_release:person.PersonResponse.student)
  
  ::person::Student* temp = student_;
  student_ = nullptr;
  return temp;
}
inline ::person::Student* PersonResponse::_internal_mutable_student() {
  
  if (student_ == nullptr) {
    auto* p = CreateMaybeMessage<::person::Student>(GetArena());
    student_ = p;
  }
  return student_;
}
inline ::person::Student* PersonResponse::mutable_student() {
  // @@protoc_insertion_point(field_mutable:person.PersonResponse.student)
  return _internal_mutable_student();
}
inline void PersonResponse::set_allocated_student(::person::Student* student) {
  ::PROTOBUF_NAMESPACE_ID::Arena* message_arena = GetArena();
  if (message_arena == nullptr) {
    delete student_;
  }
  if (student) {
    ::PROTOBUF_NAMESPACE_ID::Arena* submessage_arena =
      ::PROTOBUF_NAMESPACE_ID::Arena::GetArena(student);
    if (message_arena != submessage_arena) {
      student = ::PROTOBUF_NAMESPACE_ID::internal::GetOwnedMessage(
          message_arena, student, submessage_arena);
    }
    
  } else {
    
  }
  student_ = student;
  // @@protoc_insertion_point(field_set_allocated:person.PersonResponse.student)
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------

// -------------------------------------------------------------------

// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)

}  // namespace person

PROTOBUF_NAMESPACE_OPEN

template <> struct is_proto_enum< ::person::SexType> : ::std::true_type {};
template <>
inline const EnumDescriptor* GetEnumDescriptor< ::person::SexType>() {
  return ::person::SexType_descriptor();
}

PROTOBUF_NAMESPACE_CLOSE

// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_person_2eproto
