//1.声名语法版本
//2.声名包名称
//3.声名启用rpc
//4.枚举定义
//5.消息定义

syntax = "proto3";
package person;
option cc_generic_services = true;

enum SexType {
    unkonw = 0;
    man = 1;
    woman = 2;
};

message Student{
    int32 sn = 1;
    string name = 2;
    SexType sex = 3;
    repeated float score = 4;
    map<int32,string> other = 5;
};

message PersonRequest{
    int32 sn = 1;
}
message PersonResponse{
    Student student = 1;
}
service PersonService{
    rpc getPerson(PersonRequest) returns (PersonResponse);
}