All:test1 test2 test3
test1:test1.cc
	g++ -o test1 test1.cc -ljsoncpp -lpthread
test2:test2.cc
	g++ -o test2 test2.cc -ljsoncpp -lpthread
test3:test3.cc
	g++ -o test3 test3.cc -ljsoncpp -lpthread
clean:
	rm -f test1 test2 test3